### ISSUE TITLE
Unsupported binding namespace "http://annox.dev.java.net"

### ISSUE THREAD

**Issue by andrey-nakin** [highsource/jaxb2-annotate-plugin#49]
I'm using `jaxb2-basics-annotate` with `maven-jaxb2-plugin`. I also use `jaxb-xew-plugin` plugin.

When attempting to run `xjc` following error is displayed:

<pre>
org.xml.sax.SAXParseException; systemId: file:/home/user/myproject/myschema.xsd; lineNumber: 22; columnNumber: 2; Unsupported binding namespace "http://annox.dev.java.net". Perhaps you meant "http://github.com/jaxb-xew-plugin"?
	at com.sun.tools.xjc.reader.AbstractExtensionBindingChecker.error(AbstractExtensionBindingChecker.java:213)
	at com.sun.tools.xjc.reader.AbstractExtensionBindingChecker.checkAndEnable(AbstractExtensionBindingChecker.java:115)
	at com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement(ExtensionBindingChecker.java:133)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement(IncorrectNamespaceURIChecker.java:128)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement(CustomizationContextChecker.java:193)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.startElement(DOMForestScanner.java:147)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:244)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.importSchema(NGCCRuntimeEx.java:258)
	at com.sun.xml.xsom.impl.parser.state.importDecl.action0(importDecl.java:85)
	at com.sun.xml.xsom.impl.parser.state.importDecl.leaveElement(importDecl.java:196)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:314)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:199)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement(DOMForestScanner.java:140)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:255)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:281)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:250)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:171)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:160)
	at com.sun.tools.xjc.ModelLoader.createXSOM(ModelLoader.java:534)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:378)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:473)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:316)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
</pre>

This error appears only when compiling some schema files while I'm able to complile other schemas. I could not determine what in my schema makes the plugin failing.

**Comment by andrey-nakin** [comment]
My `pom.xml` (fragment):

<pre>
            <plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb2-plugin</artifactId>
                <version>0.13.3</version>
                <executions>
                    <execution>
                        <id>myschema</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>${basedir}/xsd</schemaDirectory>
                            <schemaIncludes>
                                <include>myschema.xsd</include>
                            </schemaIncludes>
                            <cleanPackageDirectories>false</cleanPackageDirectories>
                            <generatePackage>my.app.type</generatePackage>
                            <noFileHeader>true</noFileHeader>
                            <encoding>UTF-8</encoding>
                            <bindings>
                                <binding>
                                    <fileset>
                                        <directory>${dir.root}/xjc/bindings</directory>
                                        <includes>
                                            <include>*.xjb</include>
                                        </includes>                                    
                                    </fileset>
                                </binding>
                            </bindings>
                            <extension>true</extension>
                            <episode>true</episode>
                            <episodeFile>${basedir}/target/generated-sources/xjc/META-INF/myschema.xjb</episodeFile>
                            <args>
                                <arg>-no-header</arg>
                                <arg>-Xxew</arg>
                                <arg>-Xxew:instantiate lazy</arg>
                                <arg>-Xannotate</arg>
                            </args>
                            <plugins>
                                <plugin>
                                    <groupId>org.jvnet.jaxb2_commons</groupId>
                                    <artifactId>jaxb2-basics-annotate</artifactId>
                                    <version>1.1.0</version>
                                </plugin>
                                <plugin>
                                    <groupId>com.github.jaxb-xew-plugin</groupId>
                                    <artifactId>jaxb-xew-plugin</artifactId>
                                    <version>1.9</version>
                                </plugin>
                                <plugin>
                                    <groupId>io.swagger</groupId>
                                    <artifactId>swagger-annotations</artifactId>
                                    <version>1.5.20</version>
                                </plugin>
                                <dependency>
                                    <groupId>javax.validation</groupId>
                                    <artifactId>validation-api</artifactId>
                                </dependency>
                            </plugins>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
</pre>

**Comment by highsource** [comment]
I can't spot any problems directly.

Please provide a reproducing test project as PR in https://github.com/highsource/jaxb2-annotate-plugin-support, under, say, `a/an`.

**Comment by andrey-nakin** [comment]
@highsource Posted a pull request with an example.

**Comment by highsource** [comment]
Ok, thanks.

I see the reason. You include bindings directly in schemas but also use an episode file to avoid compiling classes. Still, XJC detects customizations and complains that they are not acknowledged.

I'll see what I can do but not quite soon.

As a workaround, move bindings to a separate bindings file and *do not* include bindings for your base schema in your dependent compilation.

**Comment by stodge** [comment]
Any updates on this? I'm having the same problem.

**Comment by stodge** [comment]
Any update on this? I have the same problem. Thanks.

**Comment by wltjr** [comment]
I also experience this issue with straight xjc and ehcache
```
[ERROR] Unsupported binding namespace "http://annox.dev.java.net". Perhaps you meant "http://java.sun.com/xml/ns/jaxb/xjc"?
  line 21 of file:/tmp/portage/dev-java/ehcache-3.8.1/work/ehcache3-3.8.1/xml/src/main/resources/ehcache-core.xsd
```

```
xjc -extension -d xml/src/main/java -p org.ehcache.xml.model \
                xml/src/main/resources/ehcache-core.xsd
```

Adding jaxb2-annotate-plugin to classpath makes no difference. I may need annox instead of jaxb2-annotate-plugin. Unless this is an upstream xjc issue. Thanks!

**Comment by laurentschoelens** [comment]
Hi @andrey-nakin / @stodge / @wltjr

Just made a PR in jaxb-ri to fix the above common problem with episode / inlined-plugin-customization in xsd.

**Comment by laurentschoelens** [comment]
Fixed in 4.0.2 of jaxb-tools due to upgrade of jaxb-ri

**Comment by aayushRedHat** [comment]
> Fixed in 4.0.2 of jaxb-tools due to upgrade of jaxb-ri

@laurentschoelens Which dependency i need to add, I have added following dependencies still getting an error: 
	```
```
<dependency>
		<groupId>org.jvnet.jaxb</groupId>
                   <artifactId>jaxb-plugins-runtime</artifactId>
                   <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
                       <artifactId>jaxb-plugin-annotate</artifactId>
                       <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugins</artifactId>
                        <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugins-tools</artifactId>
                       <version>3.0.0</version>
		</dependency>
```

Error:
```
org.xml.sax.SAXParseException: Unsupported binding namespace "http://annox.dev.java.net". Perhaps you meant "http://java.sun.com/xml/ns/jaxb/xjc"?
    at com.sun.tools.xjc.reader.AbstractExtensionBindingChecker.error (AbstractExtensionBindingChecker.java:183)
    at com.sun.tools.xjc.reader.AbstractExtensionBindingChecker.checkAndEnable (AbstractExtensionBindingChecker.java:85)
    at com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement (ExtensionBindingChecker.java:103)
    at org.xml.sax.helpers.XMLFilterImpl.startElement (XMLFilterImpl.java:539)
    at com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement (IncorrectNamespaceURIChecker.java:99)
    at org.xml.sax.helpers.XMLFilterImpl.startElement (XMLFilterImpl.java:539)
    at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement (CustomizationContextChecker.java:164)
    at org.xml.sax.helpers.XMLFilterImpl.startElement (XMLFilterImpl.java:539)

```

**Comment by laurentschoelens** [comment]
Hello @aayushRedHat 

Could you share a bigger part of the `pom.xml` ?
I'm also pretty sure you need to upgrade to v4 (for jakarta) or stay to v2 (if targeting javax)

**Comment by aayushRedHat** [comment]
> Hello @aayushRedHat
> 
> Could you share a bigger part of the `pom.xml` ? I'm also pretty sure you need to upgrade to v4 (for jakarta) or stay to v2 (if targeting javax)

```
	<dependencies>
		<dependency>
			<groupId>Internal</groupId>
			<artifactId>custom-annotations</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>Internal</groupId>
			<artifactId>commons</artifactId>
			<version>${project.version}</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
		<groupId>org.jvnet.jaxb</groupId>
<artifactId>jaxb-plugins-runtime</artifactId>
<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
                          <artifactId>jaxb-plugin-annotate</artifactId>
                          <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugins</artifactId>
                       <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugins-tools</artifactId>
                       <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j-version}</version>
		</dependency>
		<dependency>
			<groupId>X.drupal.portal.types</groupId>
			<artifactId>drupal-portal-api</artifactId>
			<version>${drupal-portal-types-version}</version>
		</dependency>
		<dependency>
			<groupId>X.drupal</groupId>
			<artifactId>drupal-api</artifactId>
			<version>1.10.10</version>
		</dependency>
		<!-- HydraTransformer Dependencies -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${slf4j-version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson-version}</version>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.9.4</version>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>4.8.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>3.0.1</version>
		</dependency>
		<dependency>
			<groupId>X.internal</groupId>
			<artifactId>auth</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.2.10</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jvnet.jaxb</groupId>
				<artifactId>jaxb-maven-plugin</artifactId>
				<version>4.0.8</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- Your JAXB plugin configuration -->
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M7</version>
				<configuration>
					<useSystemClassLoader>false</useSystemClassLoader>
				</configuration>
			</plugin>
		</plugins>
```

**Comment by laurentschoelens** [comment]
If you are using 
```xml
<groupId>org.jvnet.jaxb</groupId>
<artifactId>jaxb-maven-plugin</artifactId>
<version>4.0.8</version>
```

I'd suggest the following changes in the `pom.xml` file :
- keep `jaxb-plugins-runtime` where it is but upgrade to matching version of `jaxb-maven-plugin` (4.0.8)
- remove `jaxb-plugins-tools` (you don't need explicit dependency on it)
- move `jaxb-plugins` and `jaxb-plugin-annotate` to the `plugins` section of the `jaxb-maven-plugin` and upgrade to the matching version of `jaxb-maven-plugin` (4.0.8)

It should look in the end like this (removed non related sections regarding the issue) :

```xml
<dependencies>
    <dependency>
        <groupId>org.jvnet.jaxb</groupId>
        <artifactId>jaxb-plugins-runtime</artifactId>
        <version>4.0.8</version>
    </dependency>
</dependencies>
<build>
    <plugins>
        <plugin>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-maven-plugin</artifactId>
            <version>4.0.8</version>
            <executions>
                <execution>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <plugins>
                    <plugin>
                        <groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugin-annotate</artifactId>
                        <version>4.0.8</version>
                    </plugin>
                    <plugin>
                        <groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugins</artifactId>
                        <version>4.0.8</version>
                    </plugin>
                </plugins>
                <!-- Your JAXB plugin configuration -->
            </configuration>
        </plugin>
    </plugins>
</build>
```

NB : by using the v4 plugin, you'll be based on Jakarta XML Bind API v4 and you'll need JDK11 to run the project (even if generated code should be compatible with JDK8) since JAXB v4 is on JDK11 baseline.

**Comment by aayushRedHat** [comment]
> If you are using
> 
> ```
> <groupId>org.jvnet.jaxb</groupId>
> <artifactId>jaxb-maven-plugin</artifactId>
> <version>4.0.8</version>
> ```
> 
> I'd suggest the following changes in the `pom.xml` file :
> 
> * keep `jaxb-plugins-runtime` where it is but upgrade to matching version of `jaxb-maven-plugin` (4.0.8)
> * remove `jaxb-plugins-tools` (you don't need explicit dependency on it)
> * move `jaxb-plugins` and `jaxb-plugin-annotate` to the `plugins` section of the `jaxb-maven-plugin` and upgrade to the matching version of `jaxb-maven-plugin` (4.0.8)
> 
> It should look in the end like this (removed non related sections regarding the issue) :
> 
> ```
> <dependencies>
>     <dependency>
>         <groupId>org.jvnet.jaxb</groupId>
>         <artifactId>jaxb-plugins-runtime</artifactId>
>         <version>4.0.8</version>
>     </dependency>
> </dependencies>
> <build>
>     <plugins>
>         <plugin>
>             <groupId>org.jvnet.jaxb</groupId>
>             <artifactId>jaxb-maven-plugin</artifactId>
>             <version>4.0.8</version>
>             <executions>
>                 <execution>
>                     <goals>
>                         <goal>generate</goal>
>                     </goals>
>                 </execution>
>             </executions>
>             <configuration>
>                 <plugins>
>                     <plugin>
>                         <groupId>org.jvnet.jaxb</groupId>
>                         <artifactId>jaxb-plugin-annotate</artifactId>
>                         <version>4.0.8</version>
>                     </plugin>
>                     <plugin>
>                         <groupId>org.jvnet.jaxb</groupId>
>                         <artifactId>jaxb-plugins</artifactId>
>                         <version>4.0.8</version>
>                     </plugin>
>                 </plugins>
>                 
>             </configuration>
>         </plugin>
>     </plugins>
> </build>
> ```
> 
> NB : by using the v4 plugin, you'll be based on Jakarta XML Bind API v4 and you'll need JDK11 to run the project (even if generated code should be compatible with JDK8) since JAXB v4 is on JDK11 baseline.

Thanks @laurentschoelens I checked running with JDK 11. it is giving me following error:

```
org.xml.sax.SAXParseException: Using "http://annox.dev.java.net" customizations requires the "-Xannotate" switch to enable this plug-in.
    at com.sun.tools.xjc.reader.AbstractExtensionBindingChecker.error (AbstractExtensionBindingChecker.java:183)
    at com.sun.tools.xjc.reader.AbstractExtensionBindingChecker.checkAndEnable (AbstractExtensionBindingChecker.java:101)
    at com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement (ExtensionBindingChecker.java:103)
    at org.xml.sax.helpers.XMLFilterImpl.startElement (XMLFilterImpl.java:551)
    at com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement (IncorrectNamespaceURIChecker.java:99)
    at org.xml.sax.helpers.XMLFilterImpl.startElement (XMLFilterImpl.java:551)
    at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement (CustomizationContextChecker.java:164)
    at org.xml.sax.helpers.XMLFilterImpl.startElement (XMLFilterImpl.java:551)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.startElement (DOMForestScanner.java:117)
    at org.glassfish.jaxb.core.unmarshaller.DOMScanner.visit (DOMScanner.java:224)
    at org.glassfish.jaxb.core.unmarshaller.DOMScanner.scan (DOMScanner.java:102)

```
I checked this doc: https://github.com/highsource/jaxb2-annotate-plugin and add args in the plugin 

```
<plugin>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-maven-plugin</artifactId>
            <version>4.0.8</version>
            <executions>
                <execution>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
				<extension>true</extension>
		       <args>
			       <arg>-Xannotate</arg>
		  	       <arg>-XremoveAnnotation</arg>
		       </args>
                <plugins>
                    <plugin>
                        <groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugin-annotate</artifactId>
                        <version>4.0.8</version>
                    </plugin>
                    <plugin>
                        <groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-plugins</artifactId>
                        <version>4.0.8</version>
                    </plugin>
                </plugins>
                <!-- Your JAXB plugin configuration -->
            </configuration>
        </plugin>
```
Then it is giving me below error: 

```
[WARNING] Error while parsing schema(s).Location [ file:/Users/aaayush/Desktop/HydraModules/model/src/main/resources/address.xsd{121,14}].
org.xml.sax.SAXParseException: No JAXB customization was detected in the schema but the prefix "jaxb" is used for other namespace URIs. If you did intend to use JAXB customization, make sure the namespace URI is "https://jakarta.ee/xml/ns/jaxb"
    at com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.endDocument (IncorrectNamespaceURIChecker.java:71)
    at org.xml.sax.helpers.XMLFilterImpl.endDocument (XMLFilterImpl.java:497)
    at org.xml.sax.helpers.XMLFilterImpl.endDocument (XMLFilterImpl.java:497)
    at org.glassfish.jaxb.core.unmarshaller.DOMScanner.scan (DOMScanner.java:114)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan (DOMForestScanner.java:62)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan (DOMForestScanner.java:70)
    at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse (DOMForestParser.java:75)
    at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse (ModelLoader.java:238)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity (NGCCRuntimeEx.java:342)


```
Address.xsd:
```
<xsd:schema targetNamespace="http://www.X"
            attributeFormDefault="unqualified"
            elementFormDefault="qualified"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1"
            xmlns:tns="http://X"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:annox="http://annox.dev.java.net"
            jaxb:extensionBindingPrefixes="annox" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://annox.dev.java.net ">
```

**Comment by laurentschoelens** [comment]
I'd suggest you open a new issue here : https://github.com/highsource/jaxb-tools

This repo (https://github.com/highsource/jaxb2-annotate-plugin) has been merged in the first one (jaxb-tools) and I'd be happy to help but I think you're missing some configuration part.

What I can already say is :
- you need to remove annotations from generated source ? `<arg>-XremoveAnnotation</arg>` ?
- `xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1"` is wrong for JAXB 3/4 -> you need to move to `xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb" jaxb:version="3.0"`
- there is no schemaLocation for `annox.dev.java.net` so you can remove this part too : `xsi:schemaLocation="http://annox.dev.java.net "` and you can move to the new `urn:jaxb.jvnet.org:annox` namespace 😄
